export const FETCH_COLLECTION  = 'FETCH_COLLECTION';
export const UPDATE_COLLECTION_ITEM = 'UPDATE_COLLECTION_ITEM';
export const DELETE_COLLECTION_ITEM = 'DELETE_COLLECTION_ITEM';
export const SAVE_COLLECTION_ITEM = 'SAVE_COLLECTION_ITEM';
export const FETCH_WANTLIST  = 'FETCH_WANTLIST';
export const UPDATE_WANTLIST_ITEM = 'UPDATE_WANTLIST_ITEM';
export const DELETE_WANTLIST_ITEM = 'DELETE_WANTLIST_ITEM';
export const SAVE_WANTLIST_ITEM = 'SAVE_WANTLIST_ITEM';
